name: Terraform RG Deploy

on:
  workflow_dispatch:    # manual run
  push:
    branches: [ main, feature ]

jobs:
  terraform:
    runs-on: [self-hosted, Windows]   # ya sirf: self-hosted
    defaults:
      run:
        shell: pwsh
        # working-directory: ./terraform   # (agar tf files subfolder me hain)

    env:
      ARM_CLIENT_ID:       ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5   # optional

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out plan.tfplan

      - name: Terraform Apply (manual runs only)
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve plan.tfplan

