name: firstworkflow
on: 
  workflow_dispatch  
jobs: 
  build:
    runs-on: self-hosted
    steps:
      - name: terraform install  
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'
      - name: terraform initialisation
        run: terraform init
      - name: terraform plan
        run: terraform plan
      - name: show human-readable plan
        # ye line plan ka summary console (GitHub Actions logs) me print karegi
        run: terraform show -no-color tfplan
    
    
          
